feat(playground): merged
GreptimeTeam/dashboard pull request #195
Opened 2023-04-03 02:48 UTC by alili

2023-04-11 09:30 UTC, sunng87 commented on src/views/dashboard/playground/docs/getting-started.md
> +[Download](https://greptime.com/downloads/) GreptimeDB on your machine and
```suggestion
[Download](https://greptime.com/download/) GreptimeDB on your machine and
```

2023-04-11 09:31 UTC, sunng87 commented on src/views/dashboard/playground/docs/getting-started.md
> +Full more advanced features like scripting, various protocol support,
```suggestion
For more advanced features like scripting and protocol support,
```

2023-04-11 15:46 UTC, apdong2022 requested changes

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +Once you see the green marker, run `DESC TABLE` to check detail of the table.
```suggestion
Once the green marker appears, run `DESC TABLE` to view the details of the table.
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +- `PRIMARY KEY`: Key columns used for sorting and partition
```suggestion
- `PRIMARY KEY`: key columns that are used for sorting and partitioning
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +- `FIELD`: Value columns that hold values
```suggestion
- `FIELD`: columns which store values
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +- `TIME INDEX`: The time column
```suggestion
- `TIME INDEX`: columns of data type TIME
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +Using the `INSERT` statement is an easy way to add data to your table. Through
```suggestion
Using the `INSERT` statement to easily add data to the table. 
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +the statement below, we have inserted three rows into the `system_metrics`
```suggestion
Below example inserts three rows into the `system_metrics` 
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +Modify the value and timestamp, we can ingest more entries.
```suggestion
Ingest more entries by modifying the values and timestamps.
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +GreptimeDB supports full SQL for you to query data from a database.
```suggestion
GreptimeDB fully supports SQL.
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +Here are some query examples for the `system_metrics` so you can get familiar
```suggestion
Here are some query examples for the `system_metrics` for users to get familiar
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +with using SQL alongside GreptimeDB functions.
```suggestion
with using SQL alongside GreptimeDB's functions.
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +You can use the `GROUP BY` clause to group rows that have the same values into
```suggestion
Use the `GROUP BY` clause to group rows that have the same values into
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +Enough with the basics, try to write your own query and do some exploration.
```suggestion
Please start exploring by writing some queries!
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +-- Type your SQL here
```suggestion
-- Type SQL statements here
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +[Download](https://greptime.com/download/) GreptimeDB on your machine and
```suggestion
[Download](https://greptime.com/download/) and run GreptimeDB locally by
```

2023-04-11 15:46 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +follow our [docs](https://docs.greptime.com).
```suggestion
following [docs](https://docs.greptime.com).
```

2023-04-12 06:19 UTC, ZonaHex commented
Great work!
A couple of suggestions: 
- [ ] Delete default select from the editor. (Will do it in the main branch).
- [ ] Captcha seems to be slowing down the main page loading. Perhaps we could move it into the playground only.
- [ ] Use line(smooth) as default in Chart option. (Will do it in the main branch).

2023-04-13 04:04 UTC, apdong2022 requested changes
fine tuned the wording of Greptime Play by referring to the tool

2023-04-13 04:04 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +summary rows. The average memory usage grouped by `idc`:
```suggestion
summary rows. The code below groups average memory usage by `idc`:
```

2023-04-13 04:04 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +## Explore by Yourself
```suggestion
## Try it Out
```

2023-04-13 04:04 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +Please start exploring by writing some queries!
```suggestion
Please start exploring by writing some queries in the panel below!
```

2023-04-13 04:04 UTC, apdong2022 commented on src/views/dashboard/playground/docs/getting-started.md
> +For more advanced features like scripting and protocol support,
```suggestion
For other advanced features like scripting and protocol supports,
```

2023-04-13 06:37 UTC, ZonaHex reviewed
Great work!
A couple of suggestions: 
- [x] Delete default select from the editor. (Will do it in the main branch).
- [x] Captcha seems to be slowing down the main page loading. Perhaps we could move it into the playground only.
- [x] Use line(smooth) as default in Chart option. (Will do it in the main branch).
- [x] After Deleting the last result tab, it should not go back to the first tab.
- [ ] 'Vue warn' in the console after clicking 'run'.

2023-04-13 10:49 UTC, sunng87 approved these changes

2023-04-13 10:49 UTC, merged